### ISSUE TITLE
Wording on "Connect More Accounts" page

### ISSUE THREAD

**Issue by abisarvepalli** [Gateway-DAO/ui#652]
### Issue

Should specify **Wallet** on the _Connect More Accounts_ page

### Steps to Reproduce
> I produced this error locally using the changes on the `develop` branch

1. Pulled commit [`537e8d1b0ce40253b0de1d6708abbbf9bfe5969c`](https://github.com/Gateway-DAO/ui/blob/537e8d1b0ce40253b0de1d6708abbbf9bfe5969c/locales/en/authentication.json#L42)

2. Ran all dependent docker containers (gateway-notifier, protocol-api, dapp-backend)

3. Start UI locally and went through new user flow
    - Connect Wallet
    - Setup Email Address
    - Specify GatewayID

4. Land on _Connect More Accounts_ page

### References

https://github.com/Gateway-DAO/ui/blob/537e8d1b0ce40253b0de1d6708abbbf9bfe5969c/src/components/features/authentication/sections/completed.tsx#L70

<img width="1792" alt="image" src="https://github.com/Gateway-DAO/ui/assets/7587923/d7e8964c-e0cf-4105-91d8-ff09d993e679">

**Comment by NunoMartins21** [comment]
Waiting on your PR ser
